# -*- coding: utf-8 -*-
"""69Finder.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ADW4hhjw1lX9qWUey2kvRQIRjqVx7baf
"""

import random
winner = False
doubleWinner = False

trialTotal = 0 
trial = 0
trialDouble = 0
while doubleWinner == False:
  trialDouble = trialDouble + 1
  while winner == False:
    trialTotal += 1
    trial = trial + 1
    n = random.randint(0,1000)
    if n == 69:
      print("hehe sex " + str(n) + ". It took " + str(trial) + " tries to get here. Congrats")
      winner = True
    else:
      print("loser: " + str(n))
  if trial == 69:
    doubleWinner == True
    print("NO WAY GOOD JOB! " + "It took " + str(trialDouble) + " tries to get here. Congrats. Also this number is probably big " + str(trialTotal))
    break
  else:
    winner = False
    trial = 0